### PR TITLE
#71, #74: [First] [Cloud] Separate FirstDB from first service and port to Docker Compose

### PR DESCRIPTION
**Pull request by jakejack13**
Implements: #71, #74

### CODE REVIEW

**Comment by owenxr** [comment]
Does the `None` issue listed cause the leader to incorrectly update first?

**Comment by jakejack13** [comment]
> Does the `None` issue listed cause the leader to incorrectly update first?

Pretty sure it causes all sorts of problems. I'm going to take a closer look at it but the way that the tables are updated currently make it difficult to achieve this.

**Review by MitchellGray100 — APPROVED** [review]
LGTM

**Review by owenxr — APPROVED** [review]
LGTM

**Pull request merged**
